# Generated by Django 5.2.1 on 2025-06-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
