# Generated by Django 5.2.1 on 2025-06-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_name_alter_todo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='task_name',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='task_status',
        ),
    ]
